'use server';
/**
 * @fileOverview A photo analysis AI agent that provides feedback and ratings.
 *
 * - analyzePhotoAndSuggestImprovements - A function that handles the photo analysis process.
 * - AnalyzePhotoAndSuggestImprovementsInput - The input type for the analyzePhotoAndSuggestImprovements function.
 * - AnalyzePhotoAndSuggestImprovementsOutput - The return type for the analyzePhotoAndSuggestImprovements function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzePhotoAndSuggestImprovementsInputSchema = z.object({
  photoUrl: z
    .string()
    .url()
    .describe(
      "A publicly accessible HTTPS URL of the photo to analyze."
    ),
    language: z.string().describe('The language for the response (e.g., "tr", "en").'),
});
export type AnalyzePhotoAndSuggestImprovementsInput = z.infer<typeof AnalyzePhotoAndSuggestImprovementsInputSchema>;

const AnalyzePhotoAndSuggestImprovementsOutputSchema = z.object({
  analysis: z.string().describe('Provide a comprehensive, constructive, and friendly analysis of the photo, as if you were a photography coach. Discuss the strengths and weaknesses of the image.'),
  improvements: z
    .array(z.string())
    .describe('Provide a list of 3 concrete, actionable suggestions for improvement.'),
  rating: z
    .object({
      lighting: z.number().min(1).max(10).describe('Rate the lighting on a scale of 1-10.'),
      composition: z.number().min(1).max(10).describe('Rate the composition on a scale of 1-10.'),
      emotion: z.number().min(1).max(10).describe('Rate the emotional impact or storytelling on a scale of 1-10.'),
      overall: z.number().min(1).max(10).describe('Provide an overall rating for the photo on a scale of 1-10, based on the other criteria.'),
    })
    .describe('Provide ratings for the photo based on the specified criteria.'),
  tags: z.array(z.string()).max(10).describe('Provide up to 10 relevant tags for the photo\'s content, style, and mood (e.g., "portrait", "landscape", "street photography", "black and white", "minimalist", "happy").'),
  isAiGenerated: z.boolean().describe("Determine if the photo was generated by AI based on clues like patterns, unrealistic textures, or known AI artifacts."),
  cameraType: z.enum(['Profesyonel', 'Mobil', 'Bilinmiyor']).describe("Determine if the photo was likely taken with a professional camera (DSLR, Mirrorless) or a mobile phone. Use 'Bilinmiyor' if impossible to tell."),
  cameraMake: z.string().describe("Predicted camera make (e.g., 'Apple', 'Sony', 'Canon'). Use 'Bilinmiyor' if unsure."),
  cameraModel: z.string().describe("Predicted camera model (e.g., 'iPhone 15 Pro', 'A7 IV', 'EOS R5'). Use 'Bilinmiyor' if unsure."),
});
export type AnalyzePhotoAndSuggestImprovementsOutput = z.infer<typeof AnalyzePhotoAndSuggestImprovementsOutputSchema>;

// The main function that the application calls.
export async function analyzePhotoAndSuggestImprovements(
  input: AnalyzePhotoAndSuggestImprovementsInput
): Promise<AnalyzePhotoAndSuggestImprovementsOutput> {
  return analysisFlow(input);
}

const analysisPrompt = ai.definePrompt({
  name: 'photoAnalysisPrompt',
  input: {schema: AnalyzePhotoAndSuggestImprovementsInputSchema},
  output: {schema: AnalyzePhotoAndSuggestImprovementsOutputSchema},
  prompt: `You are a world-class photography coach named Viewora AI. Your tone is encouraging, insightful, and professional. Analyze the provided photograph and respond in the specified language: {{{language}}}.

  Your task is to provide a detailed analysis, actionable improvement tips, a rating, and detailed camera information.

  **AI Detection:** First, determine if this image was generated by AI based on clues like patterns, unrealistic textures, inconsistent lighting, or known AI artifacts (e.g., extra fingers, strange object merges). Set the \`isAiGenerated\` field to 'true' or 'false' based on this detection.

  **Camera Analysis:** If the photo is not AI-generated (\`isAiGenerated\` is false), fill in the following fields based on visual cues such as depth of field, image quality, lens distortion, etc. If the photo is AI-generated, set all these fields to 'Bilinmiyor'.
  - \`cameraType\`: Determine if the photo was taken with a 'Profesyonel' camera or a 'Mobil' device.
  - \`cameraMake\`: Predict the camera's make (e.g., 'Apple', 'Sony', 'Canon').
  - \`cameraModel\`: Predict the camera's model (e.g., 'iPhone 15 Pro', 'A7 IV', 'EOS R5').

  **IMPORTANT INSTRUCTIONS for the 'tags' field:**
  1.  Generate tags related ONLY to photography concepts. These include:
      *   **Genre:** (MUST BE THE FIRST TAG) e.g., "Portrait", "Landscape", "Street", "Macro", "Architecture", "Abstract".
      *   **Style/Technique:** e.g., "Black and White", "Minimalist", "Long Exposure", "Depth of Field".
      *   **Composition:** e.g., "Symmetry", "Leading Lines", "Negative Space".
      *   **Lighting:** e.g., "Hard Light", "Soft Light", "Golden Hour", "Backlight".
      *   **Mood/Emotion:** e.g., "Peaceful", "Dramatic", "Joyful", "Mysterious".
  2.  **DO NOT** add tags describing physical objects or people in the photo (e.g., "woman", "tree", "ring", "sea"). Focus strictly on photographic attributes.
  3.  Provide up to 10 relevant tags in the specified language: {{{language}}}.

  Analyze the photo provided: {{media url=photoUrl}}`,
});

const analysisFlow = ai.defineFlow(
  {
    name: 'analysisFlow',
    inputSchema: AnalyzePhotoAndSuggestImprovementsInputSchema,
    outputSchema: AnalyzePhotoAndSuggestImprovementsOutputSchema,
  },
  async (input) => {
    const {output} = await analysisPrompt(input);
    return output!;
  }
);
